/**
 * browser-pilot - Lightweight CDP-based browser automation
 *
 * A browser automation library built on Chrome DevTools Protocol
 * that works in Node.js, Bun, and Cloudflare Workers.
 */

// Actions & Batch Execution
export {
  type ActionEffect,
  type ActionType,
  type AssertionBeforeState,
  type AssertionScope,
  addBatchToPage,
  BatchExecutor,
  type BatchOptions,
  type BatchResult,
  type CombinatorResult,
  type Condition,
  captureBeforeState,
  captureStateSignature,
  conditionAll,
  conditionAny,
  conditionNot,
  conditionRace,
  evaluateCondition,
  evaluateOutcome,
  type MatchedCondition,
  matchText,
  matchUrl,
  NetworkResponseTracker,
  type OutcomeStatus,
  type RecordOptions,
  type RetryDecision,
  type ShouldRetryOptions,
  type Step,
  type StepResult,
  shouldRetry,
  type TextMatchMode,
  type UrlMatchMode,
  type ValidationError,
  type ValidationResult,
  validateSteps,
} from './actions/index.ts';
// Audio I/O
export {
  type AudioChunk,
  type AudioFlagOptions,
  AudioInput,
  type AudioInputState,
  AudioOutput,
  bufferToBase64,
  type CaptureOptions,
  type CaptureResult,
  calculateRMS,
  generateSilence,
  generateTone,
  getAudioChromeFlags,
  grantAudioPermissions,
  isTranscriptionAvailable,
  type PlayOptions,
  parseWavHeader,
  pcmToWav,
  type RoundTripOptions,
  type RoundTripResult,
  type TranscribeOptions,
  type TranscribeResult,
  transcribe,
} from './audio/index.ts';
// Cloudflare Access auth helpers
export {
  type CfAccessJwtResult,
  type MintCfAccessJwtOptions,
  mintCfAccessJwt,
} from './auth/index.ts';
// Browser & Page
// Includes the Phase 7 resolution / diagnostics / fuzzy-matching / structural-signature
// APIs (rankCandidates, rankSelectorCandidates, diagnoseElement, scoreElement,
// captureStructureSignature, ...). Page.resolveAll / Page.diagnose are methods on the
// Page class exported in this block.
export {
  ActionDispatchUncertainError,
  type ActionOptions,
  type ActionReceipt,
  type ActionResult,
  type AwaitReplyOptions,
  Browser,
  type BrowserOptions,
  buildFingerprintMap,
  type CandidateStrategy,
  type ComboboxConfig,
  type ComboboxResult,
  type ConsoleHandler,
  type ConsoleMessage,
  type ConsoleMessageType,
  type CustomSelectConfig,
  captureStructureSignature,
  chooseOption,
  classifyStaleError,
  computeDelta,
  connect,
  createFingerprint,
  createTargetFingerprint,
  DEFAULT_FUZZY_THRESHOLD,
  DEFAULT_MASK_ROLES,
  DEFAULT_TESTID_ATTRIBUTES,
  type DeltaChange,
  type DeltaResult,
  type DiagnoseExactResult,
  type DiagnoseFuzzyResult,
  type DiagnoseOptions,
  type DiagnoseResult,
  type Dialog,
  type DialogHandler,
  type DialogType,
  type DispatchState,
  type Download,
  detectOverlay,
  diagnoseElement,
  type ElementInfo,
  ElementNotFoundError,
  type ElementState,
  type EmitRealm,
  type EmitRealmKind,
  type EmitReply,
  type EmitResult,
  EmitTargetError,
  type EmitWsOptions,
  type EmulationState,
  type ErrorHandler,
  type ExpectNewPageOptions,
  emitWsMessage,
  extractPageState,
  extractReview,
  type FileInput,
  type FillOptions,
  type FormField,
  type FormOption,
  type FuzzyMatchOptions,
  fingerprintKey,
  fingerprintSimilarity,
  type GeolocationOptions,
  type InteractiveElement,
  isDestructiveName,
  type KeyValuePair,
  listSockets,
  NavigationError,
  type NavigationMilestone,
  type NetworkIdleOptions,
  type NewPageOptions,
  type OverlayInfo,
  Page,
  type PageError,
  type PageOptions,
  type PageSnapshot,
  type PageState,
  type PinRecoveryResult,
  type RankCandidatesOptions,
  type RankedCandidate,
  type ReadinessDiagnostics,
  type ReadyCondition,
  type ReviewResult,
  type RichSelectorCandidate,
  rankCandidates,
  rankSelectorCandidates,
  recoverPinnedTarget,
  recoverStaleRef,
  type SemanticFingerprint,
  type SnapshotNode,
  type SnapshotOptions,
  type SocketCandidate,
  type StaleErrorClassification,
  type StaleErrorKind,
  type StaleRecoveryDiagnostics,
  type StructureSignatureOptions,
  type SubmitAndVerifyOptions,
  type SubmitAndVerifyResult,
  type SubmitOptions,
  type SummaryCard,
  scoreElement,
  submitAndVerify,
  type TableData,
  type TargetFingerprint,
  type TargetNotFoundDetails,
  TargetNotFoundError,
  type TargetProvenance,
  type TargetSummary,
  TimeoutError,
  type TypeOptions,
  type UploadConfig,
  type UploadResult,
  type UserAgentMetadata,
  type UserAgentOptions,
  uploadFiles,
  type ViewportOptions,
  type WaitForOptions,
  type WaitForReadyOptions,
} from './browser/index.ts';
// CDP Client (for advanced usage)
export {
  type CDPClient,
  type CDPClientOptions,
  CDPError,
  createCDPClient,
} from './cdp/index.ts';
// Emulation
export { type DeviceDescriptor, type DeviceName, devices } from './emulation/index.ts';
// Network Interception
export {
  type ContinueRequestOptions,
  type FailRequestOptions,
  type FulfillRequestOptions,
  type InterceptedRequest,
  type RequestActions,
  type RequestHandler,
  RequestInterceptor,
  type RequestPattern,
  type ResourceType,
  type RouteOptions,
} from './network/index.ts';
// Build provenance (safe to inspect from library and CLI consumers).
export { type BuildProvenance, getBuildProvenance } from './provenance.ts';
// Providers
export {
  BrowserBaseProvider,
  BrowserEndpointResolutionError,
  BrowserlessProvider,
  type BrowserUseOptions,
  BrowserUseProvider,
  buildLocalBrowserScanTargets,
  type ChromeChannel,
  type ConnectOptions,
  type CreateSessionOptions,
  createProvider,
  discoverLocalBrowsers,
  discoverTargets,
  GenericProvider,
  getBrowserWebSocketUrl,
  type Provider,
  type ProviderSession,
  parseDevToolsActivePortFile,
  type ResolvedBrowserEndpoint,
  type ResolvedBrowserSource,
  resolveBrowserEndpoint,
  resolveChromeUserDataDirs,
} from './providers/index.ts';
// Recording/evidence artifacts.
export {
  assertRecordingManifestIntegrity,
  canonicalizeRecordingArtifact,
  createRecordingManifest,
  type RecordingAction,
  type RecordingExecution,
  type RecordingFrame,
  type RecordingIntegrityOptions,
  type RecordingIntegrityResult,
  type RecordingManifest,
  type RecordingScreenshot,
  validateRecordingManifest,
} from './recording/index.ts';
// Storage (Cookies)
export type {
  ClearCookiesOptions,
  Cookie,
  DeleteCookieOptions,
  SetCookieOptions,
} from './storage/index.ts';
// Tracing
export {
  buildWorkflowSummary,
  disableTracing,
  enableTracing,
  formatWorkflowSummary,
  getTracer,
  type TraceCategory,
  type TraceEvent,
  type TraceLevel,
  Tracer,
  type TracerOptions,
  type WorkflowStepSummary,
  type WorkflowSummary,
} from './trace/index.ts';
// Waiting utilities
export {
  type WaitOptions,
  type WaitResult,
  type WaitState,
  waitForAnyElement,
  waitForElement,
  waitForNavigation,
  waitForNetworkIdle,
  waitForReady,
} from './wait/index.ts';
