/**
 * browser-pilot - Lightweight CDP-based browser automation
 *
 * A browser automation library built on Chrome DevTools Protocol
 * that works in Node.js, Bun, and Cloudflare Workers.
 */

// Actions & Batch Execution
export {
  type ActionEffect,
  type ActionType,
  type AssertionBeforeState,
  type AssertionScope,
  addBatchToPage,
  BatchExecutor,
  type BatchOptions,
  type BatchResult,
  type CombinatorResult,
  type Condition,
  captureBeforeState,
  captureStateSignature,
  conditionAll,
  conditionAny,
  conditionNot,
  conditionRace,
  evaluateCondition,
  evaluateOutcome,
  type MatchedCondition,
  matchText,
  matchUrl,
  NetworkResponseTracker,
  type OutcomeStatus,
  type RecordOptions,
  type RetryDecision,
  type ShouldRetryOptions,
  type Step,
  type StepResult,
  shouldRetry,
  type TextMatchMode,
  type UrlMatchMode,
  type ValidationError,
  type ValidationResult,
  validateSteps,
} from './actions/index.ts';
export type { RecordingIo } from './actions/types.ts';
export { ConnectionSessionOwner } from './adapters/node/session-owner.ts';
// Audio I/O
export {
  type AudioChunk,
  type AudioFlagOptions,
  AudioInput,
  type AudioInputState,
  AudioOutput,
  bufferToBase64,
  type CaptureOptions,
  type CaptureResult,
  calculateRMS,
  generateSilence,
  generateTone,
  getAudioChromeFlags,
  grantAudioPermissions,
  isTranscriptionAvailable,
  type PlayOptions,
  parseWavHeader,
  pcmToWav,
  type RoundTripOptions,
  type RoundTripResult,
  type TranscribeOptions,
  type TranscribeResult,
  transcribe,
} from './audio/index.ts';
// Cloudflare Access auth helpers
// Cookie state capture/restore (Cloudflare Access / cookie-based auth persistence)
export {
  type CfAccessJwtResult,
  type CookieCaptureOptions,
  type CookieRestoreResult,
  type CookieState,
  CookieStateError,
  type CookieStateErrorCode,
  captureCookieState,
  type MintCfAccessJwtOptions,
  mintCfAccessJwt,
  parseCookieState,
  restoreCookieState,
  type SerializedCookie,
  serializeCookieState,
} from './auth/index.ts';
export { Browser as PortableBrowser } from './browser/browser.ts';
// Browser & Page
export {
  CapabilityCache,
  type CapabilityEvidence,
  type CapabilityReport,
  type CapabilityState,
} from './browser/capabilities.ts';
// Includes the Phase 7 resolution / diagnostics / fuzzy-matching / structural-signature
// APIs (rankCandidates, rankSelectorCandidates, diagnoseElement, scoreElement,
// captureStructureSignature, ...). Page.resolveAll / Page.diagnose are methods on the
// Page class exported in this block.
export {
  ActionDispatchUncertainError,
  type ActionOptions,
  type ActionReceipt,
  type ActionResult,
  type AwaitReplyOptions,
  Browser,
  type BrowserOptions,
  buildFingerprintMap,
  type CandidateStrategy,
  type ComboboxConfig,
  type ComboboxResult,
  type ConsoleHandler,
  type ConsoleMessage,
  type ConsoleMessageType,
  type CustomSelectConfig,
  captureStructureSignature,
  chooseOption,
  classifyStaleError,
  computeDelta,
  connect,
  createFingerprint,
  createTargetFingerprint,
  DEFAULT_FUZZY_THRESHOLD,
  DEFAULT_MASK_ROLES,
  DEFAULT_TESTID_ATTRIBUTES,
  type DeltaChange,
  type DeltaResult,
  type DiagnoseExactResult,
  type DiagnoseFuzzyResult,
  type DiagnoseOptions,
  type DiagnoseResult,
  type Dialog,
  type DialogHandler,
  type DialogType,
  type DispatchState,
  type Download,
  detectOverlay,
  diagnoseElement,
  type ElementInfo,
  ElementNotFoundError,
  type ElementState,
  type EmitRealm,
  type EmitRealmKind,
  type EmitReply,
  type EmitResult,
  EmitTargetError,
  type EmitWsOptions,
  type EmulationState,
  type ErrorHandler,
  type ExpectNewPageOptions,
  emitWsMessage,
  extractPageState,
  extractReview,
  type FileInput,
  type FillOptions,
  type FormField,
  type FormOption,
  type FuzzyMatchOptions,
  fingerprintKey,
  fingerprintSimilarity,
  type GeolocationOptions,
  type InteractiveElement,
  isDestructiveName,
  type KeyValuePair,
  type LocalEndpointRequest,
  type LocalEndpointResolver,
  listSockets,
  NavigationError,
  type NavigationMilestone,
  type NetworkIdleOptions,
  type NewPageOptions,
  type OverlayInfo,
  Page,
  type PageError,
  type PageOptions,
  type PageSnapshot,
  type PageState,
  type PinRecoveryResult,
  type RankCandidatesOptions,
  type RankedCandidate,
  type ReadinessDiagnostics,
  type ReadyCondition,
  type ReviewResult,
  type RichSelectorCandidate,
  rankCandidates,
  rankSelectorCandidates,
  recoverPinnedTarget,
  recoverStaleRef,
  type SemanticFingerprint,
  type SnapshotNode,
  type SnapshotOptions,
  type SocketCandidate,
  type StaleErrorClassification,
  type StaleErrorKind,
  type StaleRecoveryDiagnostics,
  type StructureSignatureOptions,
  type SubmitAndVerifyOptions,
  type SubmitAndVerifyResult,
  type SubmitOptions,
  type SummaryCard,
  scoreElement,
  submitAndVerify,
  type TableData,
  type TargetFingerprint,
  type TargetNotFoundDetails,
  TargetNotFoundError,
  type TargetProvenance,
  type TargetSummary,
  TimeoutError,
  type TypeOptions,
  type UploadConfig,
  type UploadResult,
  type UserAgentMetadata,
  type UserAgentOptions,
  uploadFiles,
  type ViewportOptions,
  type WaitForOptions,
  type WaitForReadyOptions,
} from './browser/index.ts';
// CDP Client (for advanced usage)
export {
  type CDPClient,
  type CDPClientOptions,
  CDPError,
  createCDPClient,
} from './cdp/index.ts';
export type { Transport, TransportFactory, TransportOptions } from './cdp/transport.ts';
// Optional host integration contracts.
export {
  type ArtifactPutOptions,
  type ArtifactPutResult,
  type ArtifactSink,
  CapabilityError,
  type Clock,
  type ExecutionContext,
  type OperationContext,
  type SecretsPort,
  type SessionHandle,
  type SessionOpenOptions,
  type SessionOwner,
} from './core/ports.ts';
export type {
  BorrowedBrowser,
  BrowserLease,
  ConnectionSessionOwnerOptions,
  SessionOwnerV2,
  SessionStatus,
} from './core/sessions/owner.ts';
// Emulation
export { type DeviceDescriptor, type DeviceName, devices } from './emulation/index.ts';
// Network Interception
export {
  type ContinueRequestOptions,
  type FailRequestOptions,
  type FulfillRequestOptions,
  type InterceptedRequest,
  type RequestActions,
  type RequestHandler,
  RequestInterceptor,
  type RequestPattern,
  type ResourceType,
  type RouteOptions,
} from './network/index.ts';
// Build provenance (safe to inspect from library and CLI consumers).
export { type BuildProvenance, getBuildProvenance } from './provenance.ts';
// Providers
export {
  assertProviderConstraint,
  BrowserBaseProvider,
  BrowserEndpointResolutionError,
  BrowserlessProvider,
  type BrowserUseOptions,
  BrowserUseProvider,
  buildLocalBrowserScanTargets,
  type ChromeChannel,
  CloudflareProvider,
  type CloudflareProviderOptions,
  type ConnectOptions,
  type CreateSessionOptions,
  createProvider,
  discoverLocalBrowsers,
  discoverTargets,
  GenericProvider,
  getBrowserWebSocketUrl,
  type NormalizedProviderSelector,
  normalizeProviderSelector,
  type Provider,
  type ProviderFactoryPorts,
  type ProviderReleaseResult,
  type ProviderSession,
  parseDevToolsActivePortFile,
  type ResolvedBrowserEndpoint,
  type ResolvedBrowserSource,
  resolveBrowserEndpoint,
  resolveChromeUserDataDirs,
} from './providers/index.ts';
export type {
  CloudflareChromiumOptions,
  CloudflareEngine,
  CloudflareKitesurfOptions,
  ProviderConnection,
  ProviderId,
  ProviderSelection,
  ProviderSelector,
} from './providers/types.ts';
// Recording/evidence artifacts.
export {
  assertRecordingManifestIntegrity,
  canonicalizeRecordingArtifact,
  createRecordingManifest,
  Recorder,
  type RecorderCaptureStatus,
  type RecorderEventContext,
  type RecorderListenOptions,
  type RecorderMarker,
  type RecorderOptions,
  type RecordingAction,
  type RecordingExecution,
  type RecordingFrame,
  type RecordingIntegrityOptions,
  type RecordingIntegrityResult,
  type RecordingManifest,
  type RecordingScreenshot,
  validateRecordingManifest,
} from './recording/index.ts';
export type { FullRecordingOutput, RawRecordedEvent } from './recording/types.ts';
// Runtime env override hook (e.g. Cloudflare Workers without process.env).
export { clearEnvOverrides, setEnvOverrides, withEnv } from './runtime/env.ts';
// Storage (Cookies)
export type {
  ClearCookiesOptions,
  Cookie,
  DeleteCookieOptions,
  SetCookieOptions,
} from './storage/index.ts';
// Tracing
export {
  buildWorkflowSummary,
  disableTracing,
  enableTracing,
  formatWorkflowSummary,
  getTracer,
  type TraceCategory,
  type TraceEvent,
  type TraceLevel,
  Tracer,
  type TracerOptions,
  type WorkflowStepSummary,
  type WorkflowSummary,
} from './trace/index.ts';
// Waiting utilities
export {
  type WaitOptions,
  type WaitResult,
  type WaitState,
  waitForAnyElement,
  waitForElement,
  waitForNavigation,
  waitForNetworkIdle,
  waitForReady,
} from './wait/index.ts';
// WebMCP page-agent bridge (discovery and invocation remain in-page).
export {
  type WebMCPListResult,
  type WebMCPStatus,
  type WebMCPToolAnnotations,
  type WebMCPToolDescriptor,
  webmcpCall,
  webmcpList,
  webmcpStatus,
} from './webmcp/client.ts';
