/**
 * browser-pilot - Lightweight CDP-based browser automation
 *
 * A browser automation library built on Chrome DevTools Protocol
 * that works in Node.js, Bun, and Cloudflare Workers.
 */

// Actions & Batch Execution
export {
  type ActionType,
  addBatchToPage,
  BatchExecutor,
  type BatchOptions,
  type BatchResult,
  type CombinatorResult,
  type Condition,
  captureStateSignature,
  conditionAll,
  conditionAny,
  conditionNot,
  conditionRace,
  evaluateCondition,
  evaluateOutcome,
  type MatchedCondition,
  NetworkResponseTracker,
  type OutcomeStatus,
  type RecordOptions,
  type Step,
  type StepResult,
  type ValidationError,
  type ValidationResult,
  validateSteps,
} from './actions/index.ts';
// Audio I/O
export {
  type AudioChunk,
  type AudioFlagOptions,
  AudioInput,
  type AudioInputState,
  AudioOutput,
  bufferToBase64,
  type CaptureOptions,
  type CaptureResult,
  calculateRMS,
  generateSilence,
  generateTone,
  getAudioChromeFlags,
  grantAudioPermissions,
  isTranscriptionAvailable,
  type PlayOptions,
  parseWavHeader,
  pcmToWav,
  type RoundTripOptions,
  type RoundTripResult,
  type TranscribeOptions,
  type TranscribeResult,
  transcribe,
} from './audio/index.ts';
// Browser & Page
export {
  type ActionOptions,
  type ActionResult,
  Browser,
  type BrowserOptions,
  buildFingerprintMap,
  type ComboboxConfig,
  type ComboboxResult,
  type ConsoleHandler,
  type ConsoleMessage,
  type ConsoleMessageType,
  type CustomSelectConfig,
  chooseOption,
  computeDelta,
  connect,
  createFingerprint,
  createTargetFingerprint,
  type DeltaChange,
  type DeltaResult,
  type Dialog,
  type DialogHandler,
  type DialogType,
  type Download,
  detectOverlay,
  type ElementInfo,
  ElementNotFoundError,
  type EmulationState,
  type ErrorHandler,
  extractPageState,
  extractReview,
  type FileInput,
  type FillOptions,
  type FormField,
  type FormOption,
  fingerprintKey,
  fingerprintSimilarity,
  type GeolocationOptions,
  type InteractiveElement,
  type KeyValuePair,
  NavigationError,
  type NetworkIdleOptions,
  type OverlayInfo,
  Page,
  type PageError,
  type PageOptions,
  type PageSnapshot,
  type PageState,
  type PinRecoveryResult,
  type ReviewResult,
  recoverPinnedTarget,
  recoverStaleRef,
  type SemanticFingerprint,
  type SnapshotNode,
  type SnapshotOptions,
  type SubmitAndVerifyOptions,
  type SubmitAndVerifyResult,
  type SubmitOptions,
  type SummaryCard,
  submitAndVerify,
  type TableData,
  type TargetFingerprint,
  TimeoutError,
  type TypeOptions,
  type UploadConfig,
  type UploadResult,
  type UserAgentMetadata,
  type UserAgentOptions,
  uploadFiles,
  type ViewportOptions,
  type WaitForOptions,
} from './browser/index.ts';
// CDP Client (for advanced usage)
export {
  type CDPClient,
  type CDPClientOptions,
  CDPError,
  createCDPClient,
} from './cdp/index.ts';
// Emulation
export { type DeviceDescriptor, type DeviceName, devices } from './emulation/index.ts';
// Network Interception
export {
  type ContinueRequestOptions,
  type FailRequestOptions,
  type FulfillRequestOptions,
  type InterceptedRequest,
  type RequestActions,
  type RequestHandler,
  RequestInterceptor,
  type RequestPattern,
  type ResourceType,
  type RouteOptions,
} from './network/index.ts';
// Providers
export {
  BrowserBaseProvider,
  BrowserEndpointResolutionError,
  BrowserlessProvider,
  type BrowserUseOptions,
  BrowserUseProvider,
  buildLocalBrowserScanTargets,
  type ChromeChannel,
  type ConnectOptions,
  type CreateSessionOptions,
  createProvider,
  discoverLocalBrowsers,
  discoverTargets,
  GenericProvider,
  getBrowserWebSocketUrl,
  type Provider,
  type ProviderSession,
  parseDevToolsActivePortFile,
  type ResolvedBrowserEndpoint,
  type ResolvedBrowserSource,
  resolveBrowserEndpoint,
  resolveChromeUserDataDirs,
} from './providers/index.ts';
// Storage (Cookies)
export type {
  ClearCookiesOptions,
  Cookie,
  DeleteCookieOptions,
  SetCookieOptions,
} from './storage/index.ts';
// Tracing
export {
  buildWorkflowSummary,
  disableTracing,
  enableTracing,
  formatWorkflowSummary,
  getTracer,
  type TraceCategory,
  type TraceEvent,
  type TraceLevel,
  Tracer,
  type TracerOptions,
  type WorkflowStepSummary,
  type WorkflowSummary,
} from './trace/index.ts';
// Waiting utilities
export {
  type WaitOptions,
  type WaitResult,
  type WaitState,
  waitForAnyElement,
  waitForElement,
  waitForNavigation,
  waitForNetworkIdle,
} from './wait/index.ts';
